#!/usr/bin/env python
# Copyright 2019-2020 Francois Blackburn
# SPDX-License-Identifier: GPL-3.0-or-later

import os
import re
import uvicorn
from fastapi import Body, FastAPI
from pydantic import BaseModel, Field

app = FastAPI()

API_LISTEN = os.getenv('API_LISTEN', '0.0.0.0')
API_PORT = int(os.getenv('API_PORT', 6789))
NEXTCLOUD_PATH = os.getenv('NEXTCLOUD_PATH', '/var/www/html')

CONFIG_FILE = os.path.join(NEXTCLOUD_PATH, 'config/config.php')
MAINTENANCE_REGEX = r'(^.*maintenance.*)(?:false|true)(.*$)'


class Maintenance(BaseModel):
    enabled: bool = Field(..., title='set nextcloud into maintenance mode')


@app.put("/api/maintenance")
async def update_maintenance(maintenance: Maintenance = Body(...)):
    state = 'true' if maintenance.enabled else 'false'
    _write_state(state)


def _write_state(state: str):
    with open(CONFIG_FILE, 'r+') as f:
        content = f.read()
        output = re.sub(
            MAINTENANCE_REGEX,
            r'\1{}\2'.format(state),
            content,
            flags=re.MULTILINE,
        )
        f.seek(0)
        f.write(output)
        f.truncate()


if __name__ == '__main__':
    uvicorn.run(app, host=API_LISTEN, port=API_PORT, log_level="debug")
